### ISSUE TITLE
No errors output when composer.json is invalid

### ISSUE THREAD

**Issue by alexander-schranz** [ramsey/composer-install#85]
When example pushing the composer.json with a invalid whitespace character the composer install action does not show the error which did happened:

https://github.com/sulu/SuluHeadlessBundle/runs/1887128062?check_suite_focus=true

![Bildschirmfoto 2021-02-12 um 13 34 14](https://user-images.githubusercontent.com/1698337/107768680-1f424e00-6d37-11eb-8ca0-0c0a0541cc9c.png)

Not sure if this is a problem with github actions or the implementation I'm sadly not familiar enough who does handle this.
When running the command itself the correct error is shown:

```
~/D/S/s/v/sulu/headless-bundle (feature/php-8-compatibility|✔) $ composer update


  [UnexpectedValueException]
  Could not parse version constraint  2.*: Invalid version string " 2.*"
  ```

**Comment by ramsey** [comment]
Comment from @Kocal on https://github.com/ramsey/composer-install/issues/58#issuecomment-791889189: 

> Hum, I'm trying to use the new release since #93 has been merged, but I have error `The process '/usr/local/bin/composer' failed with exit code 1`. That's weird since checks from #93 were all green... 😓 
> 
> ![image](https://user-images.githubusercontent.com/2103975/110198791-4501d500-7e55-11eb-9def-ac39ca0dffb4.png)
> 
> @ramsey do you have an idea how can I debug this? Since it's working on the action's CI but not on other CI, I don't know where and how to start 😞 
> Thanks!

**Comment by ramsey** [comment]
To clarify, I don't think these two errors are related, but we do need some better error messaging when composer fails like this, to make it easier to debug.

**Comment by Kocal** [comment]
I started working on this and I found something interesting. 

Using the following step on two repositories (my fork https://github.com/Kocal/composer-install/pull/2 and another private repo which needs `working-directory`)
```yaml
-   uses: ramsey/composer-install@v1
    with:
        dependency-versions: locked
        composer-options: --unknown-option
```

I'm having different outputs: 
- the fork, I have all the infos I need (https://github.com/Kocal/composer-install/runs/2050396017?check_suite_focus=true#step:4:12): 
![image](https://user-images.githubusercontent.com/2103975/110239727-bb333400-7f48-11eb-9e59-47614ddebd48.png)
- the other private repo, I have literally nothing:
![image](https://user-images.githubusercontent.com/2103975/110239735-c9815000-7f48-11eb-9127-f5550c07c7ba.png)

I don't know why do we have different outputs... Maybe because we run the action on the action's repo?

**Comment by ramsey** [comment]
It might have to do with the type of error. In the fork, you're passing it an option that Composer doesn't know about. In the private repo, I don't know what's causing the error, so

**Comment by jrfnl** [comment]
Just a heads-up: I ran into the `'usr/local/bin/composer' failed with exit code 1` error myself today.
In my case, the cause was a silly typo in the `composer.json`.

Might it be an idea to run `composer validate --strict` before running the `composer install` and to exit with the output of the validate command if that fails ? That would probably catch most issues and should show a more helpful error message.

**Comment by ramsey** [comment]
Good idea, @jrfnl!

**Comment by alexander-schranz** [comment]
The `validate` command will fail in none libraries like a symfony based project e.g.:

```bash
composer create-project symfony/skeleton
cd skeleton
composer validate --strict
```

Will fail with:

```bash
name : The property name is required
description : The property description is required
```

Also in our cases linting is an own task in our CIs, so I would not add this as part of the installation.

**Comment by jrfnl** [comment]
@alexander-schranz Just `composer validate` (without the `strict`) should get round that and should still provide more usable error messages, so I think it's still a viable solution.

**Comment by ramsey** [comment]
The latest version (`2.0.1`) includes `composer.json` validation and emits an error in the GitHub Action runner, if it encounters a validation error.
